### ISSUE TITLE
C53 has "junk data" in header and footer?

### ISSUE THREAD

**Issue by Herrie82** [node-ebics/node-ebics-client#37] opened 2020-05-27 07:27 UTC
I'm trying to get C53 statements instead of STA for one of our projects, however it seems that the XML I get has some header & footer information in there. Not sure how to deal with this properly?

<img width="1280" alt="XML1" src="https://user-images.githubusercontent.com/2158028/82990248-2df7a200-9ffc-11ea-8bf1-5c5089059110.png">
<img width="1265" alt="xml2" src="https://user-images.githubusercontent.com/2158028/82990254-3223bf80-9ffc-11ea-8ccd-42779f535792.png">

I'm simply using the following code now:

`const data = Buffer.from(resp.orderData);
 fs.writeFile("myfilename.dat", data.toString('utf8'), function (err)`

**Comment by jpbuttet** [comment] 2020-06-03 14:10
Hello, same issue trying to dowload C53 from Credit-Suisse. I also get some "junk data". Any hints ?

**Comment by Herrie82** [comment] 2020-06-03 14:14
> Hello, same issue trying to dowload C53 from Credit-Suisse. I also get some "junk data". Any hints ?

Do you have similar "junk data" in there? Or something else in terms of format?

**Comment by jpbuttet** [comment] 2020-06-03 15:19
> 
> 
> > Hello, same issue trying to dowload C53 from Credit-Suisse. I also get some "junk data". Any hints ?
> 
> Do you have similar "junk data" in there? Or something else in terms of format?

hello, thank you for your reply, please find here attached one screenshot of the file that I can download with send-c53.order

Best regards.

![Capture](https://user-images.githubusercontent.com/7593186/83655191-6714b100-a5be-11ea-8529-a9d368ef0cd2.JPG)

**Comment by jpbuttet** [comment] 2020-06-03 15:23
an other one:
![Capture](https://user-images.githubusercontent.com/7593186/83655684-fa4de680-a5be-11ea-84cd-da3156f6d364.JPG)

**Comment by Herrie82** [comment] 2020-06-03 15:28
OK so seems we have similar issue. It might be due to XML being streams and they would need to be saved differently. I'm sure @nanov might have some thoughts or solutions. I understood he has it in production with a number of banks.

**Comment by jpbuttet** [comment] 2020-06-03 15:33
I am also trying to download camt.053 from one other Swiss Bank. Banque Cantonale du Valais. This bank uses EBICS as a service from Swisscom.
Result is even worse:
![Capture](https://user-images.githubusercontent.com/7593186/83656835-5a915800-a5c0-11ea-9843-0c3f6dcb0db8.JPG)

**Comment by jpbuttet** [comment] 2020-06-08 08:49
Hello,
Couldn’t solve the “junk data” issue until now, but I have one comment to do and one question to raise related to my last message  regarding Banque Cantonale du Valais (régional swiss bank):

I could find out that the Ebics server of this bank delivers the camt.053 file in xml format without any zip container. That’s probably the reason  why the message is not readable when downloaded with send-c53.order. 
My question is following:
Is it possible to change an Ebics-client parameter in order to download non zipped camt.53 message ? Any hints ?

Best reagards.

**Comment by ernho** [comment] 2020-06-29 12:58
> Hello,
> Couldn’t solve the “junk data” issue until now, but I have one comment to do and one question to raise related to my last message regarding Banque Cantonale du Valais (régional swiss bank):
> 
> I could find out that the Ebics server of this bank delivers the camt.053 file in xml format without any zip container. That’s probably the reason why the message is not readable when downloaded with send-c53.order.
> My question is following:
> Is it possible to change an Ebics-client parameter in order to download non zipped camt.53 message ? Any hints ?
> 
> Best reagards.

Thank you for your hint. Had the same issue you can find in the code lib/orders/H004/response.js orderData 	return zlib.inflateSync(data); here the data is unzipped. so you dont need to call zlib.inflateSync

**Comment by jpbuttet** [comment] 2020-06-30 06:53
Hello ernho,
Thank you for your reply.

I already tried to replace the last line

return zlib.inflateSync(data);

simply with

return data;

... but after this change, the outcome of send-c53-order.js was not a readable xml file.

How did you manage to get readable xml file in this way ?


Best regards.

**Comment by ernho** [comment] 2020-06-30 11:56
@jpbuttet the bank sends back a zip folder. 
maybe this is confusing but zlib.inflateSync(data)  decompresses the chunk data. so you have to save that data on the drive as zip and then decompress it. 

50 4B is the header of zip

![HEX-OFzip](https://user-images.githubusercontent.com/4853679/86123249-6bf35480-bad9-11ea-809b-29f2f1bb825c.PNG)

**Comment by jpbuttet** [comment] 2020-07-01 18:45
@ernho You wrote "the bank sends back a zip folder" 
No, as I wrote, this particular bank delivers files in xml format without zip container.
My question is : did you manage to get readable outcome when the bank delivers non zipped camt-053 files ?

**Comment by ernho** [comment] 2020-07-02 09:19
@jpbuttet maybe you got me wrong but the problem is that the bank delivers a zipped folder with xml files. your output of hex helped me to understand that. 50 4B is the header of a zipped folder

if you still have the file myfilename_22mai_02_juin.dat rename it to myfilename_22mai_02_juin.zip. 

so in future save the data like

`		let date = new moment().format('YYYYMMDD');
			const data = Buffer.from(resp.orderData);
			let distPath = baseDir + '/Camt53_sgkb_' +date + '.zip'; 
			const dstZip = fs.createWriteStream(distPath);
			dstZip.write(data);
			dstZip.end();
`

 then you can unpack it and you will  find camt54 xml files there. reason is that if the account has more then one account, depot and so on the bank delivers it as zipped folder. I had the same issue with St. Gallener Kantonal Bank and the one you are trying to fetch :)

**Comment by jpbuttet** [comment] 2020-07-03 06:11
@ernho 
Thank you very much, the solution you suggested works like a charm at least for Credit Suisse bank, the result is a perfect zip archive containing all the xml file.
Next week I will test your solution with the other bank that is problematic (Banque Cantonale du Valais).

@Herrie82 
The way of saving the data suggested by ernho seems to solve the issue related to “Junk data”.

Best regards.

**Comment by jpbuttet** [comment] 2020-07-06 09:04
@ernho

I could test send-c53-order.js modified according your suggestion and it worked perfectly.
I could download camt.053 files from the BCVs (Banque Cantonale du Valais).

Thank you very much for your help.
Best regards.

T

**Comment by ernho** [comment] 2020-07-06 15:34
@jpbuttet you are welcome so we can close this issue because bank does not send "junk data" the data received is sometimes zip and has to be proceeded differently .

**Closed** 2021-03-22 17:25 UTC

**Comment by Herrie82** [comment] 2021-03-25 11:02
I added some sample code for downloading CAMT in ZIP format. See https://github.com/node-ebics/node-ebics-client/pull/48
